version: "3"

services:
  virtuoso:
    container_name: virtuoso
    image: "openlink/virtuoso-opensource-7"
    volumes:
      - virtuosodb:/database
    env_file:
      - .env
    ports:
      - 8890:8890
      - 1111:1111
  
  lodview:
    container_name: lodview
    build:
      context: lodview/
    env_file:
      - .env
    ports:
      - 9090:8080
  
  datareports:
    container_name: datareports
    build:
      context: .
      dockerfile: Dockerfile.datareports
    ports:
      - 3000:3000

    
  graphdb:
    container_name: graphdb
    image: "ontotext/graphdb:10.0.2"
    volumes:
      - graphdb:/opt/graphdb/home
    ports:
      - "7200:7200"


volumes:
  virtuosodb:
  graphdb: