FROM node:current-alpine as builder

WORKDIR /app

COPY datareports/package*.json ./

RUN npm ci
RUN npm audit fix

COPY datareports .
COPY .env ./

RUN npm run build

FROM node:current-alpine

WORKDIR /app

COPY --from=builder /app/build .
COPY --from=builder /app/package*.json .
COPY --from=builder /app/node_modules ./node_modules

EXPOSE 3000

CMD ["node", "index.js"]