version: "3"

services:
  virtuoso:
    container_name: virtuoso
    image: "openlink/virtuoso-opensource-7"
    volumes:
      - virtuosodb:/database
    env_file:
      - .env
    ports:
      - 8890:8890
      - 1111:1111
  
  lodview:
    container_name: lodview
    build:
      context: lodview/
    env_file:
      - .env
    ports:
      - 9090:8080

volumes:
  virtuosodb: